### PR TITLE
Update to libssh2 1.8.1

### PR DESCRIPTION
**Pull request by cmb69**

### CODE REVIEW

**Comment by Jan-E** [comment]
@cmb69 Is this just an unchanged import of libssh 1.8.1 or are there winlibs-specific changes?

**Comment by cmb69** [comment]
This is just an unmodified import.

**Comment by Jan-E** [comment]
OK, thx

**Comment by weltling** [comment]
Merged, thanks!

**Comment by Jan-E** [comment]
There were 2 commits to the 1.8.1 branch after the release:
https://github.com/libssh2/libssh2/commits/1.8.1

Fixed misapplied patch:
https://github.com/libssh2/libssh2/commit/ca2744483eac4e707084df5fc55cc69d57571dde

moved MAX size declarations
https://github.com/libssh2/libssh2/commit/d06ab72a146be1a5975d351e747cebe9f2b5357a

**Comment by cmb69** [comment]
@weltling Looks like these are bug fixes – should we backport these right away?

**Comment by weltling** [comment]
@cmb69 the second one doesn't fix anything at runtime. The first one could be a bugfix, yes. I'd prefer to omit these, as long as no bug has been reported and PHP's tests pass, especially as we're in the QA phase for the current RCs right now.

Thanks.

**Comment by cmb69** [comment]
@weltling Fine. Thanks.

**Comment by Jan-E** [comment]
How do you run the tests for the ssh2 extension? Against a public test-server, against a vagrant box?

**Pull request closed without merging**
